---
# tasks file for ip-forwarder
- name: Enable IPv4 forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ipfwd.ipv4 is defined and ipfwd.ipv4

- name: Enable IPv6 forwarding
  become: true
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: ipfwd.ipv6 is defined and ipfwd.ipv6

- name: Enable NAT
  become: true
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ ipfwd.wan }}"
    jump: MASQUERADE
