---
# tasks file for ip-forwarder

- name: Enable IPv4 forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: gw.ipfwd.ipv4 is defined and gw.ipfwd.ipv4.enabled is defined and gw.ipfwd.ipv4.enabled

- name: Enable IPv6 forwarding
  become: true
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  when: gw.ipfwd.ipv6 is defined and gw.ipfwd.ipv6.enabled is defined and gw.ipfwd.ipv6.enabled

- name: Enable IPv4 NAT
  become: true
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ gw.ipfwd.ipv4.nat.wan }}"
    jump: MASQUERADE
  when: gw.ipfwd.ipv4.nat is defined and gw.ipfwd.ipv4.nat.enabled is defined and gw.ipfwd.ipv4.nat.enabled

- name: Install iptables-persistent apt packages
  become: true
  apt:
    update_cache: true
    name: iptables-persistent
    state: present

- name: Persist IPv4 iptables rules
  become: true
  shell: iptables-save >/etc/iptables/rules.v4
  when: gw.ipfwd.ipv4 is defined and gw.ipfwd.ipv4.enabled is defined and gw.ipfwd.ipv4.enabled

- name: Persist IPv6 iptables rules
  become: true
  shell: ip6tables-save >/etc/iptables/rules.v6
  when: gw.ipfwd.ipv6 is defined and gw.ipfwd.ipv6.enabled is defined and gw.ipfwd.ipv6.enabled
